name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade buildozer
        pip install cython  # Install Cython
    - name: Build with Buildozer
      run: |
        buildozer android debug

    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: bin/*.apk
