name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      # Get the current date
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u '+%Y%m%d')"
        shell: bash

      # Cache the Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Cache the Buildozer build directory
      - name: Cache Buildozer build directory
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --user buildozer

      # Build the project with Buildozer
      - name: Build with Buildozer
        run: buildozer android debug

      # Upload build artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: bin/*.apk
