name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install --upgrade buildozer
        pip install cython  # Install Cython

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d $HOME/cmdline-tools
        export ANDROID_HOME=$HOME/android-sdk
        mkdir -p $ANDROID_HOME
        mkdir -p $ANDROID_HOME/cmdline-tools
        mv $HOME/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        echo "export ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/emulator:$PATH" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/tools:$PATH" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/tools/bin:$PATH" >> $GITHUB_ENV
        source $GITHUB_ENV
        sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Build with Buildozer
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        buildozer android debug

    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: bin/*.apk
