name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # الإصدار الأحدث

    - name: Set up Python
      uses: actions/setup-python@v4  # الإصدار الأحدث
      with:
        python-version: '3.11'  # Python 3.11

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip build-essential git
        pip install --upgrade cython
        pip install kivy
        pip install buildozer
        pip install tensorflow  # تثبيت TensorFlow
        # تثبيت المكتبات الأخرى التي يحتاجها مشروعك
        pip install -r requirements.txt

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: myapp-apk
        path: bin/*.apk
